### ISSUE TITLE
Change `Falco Alerts` to `Falco Outputs`

### ISSUE THREAD

**Issue by incertum** [falcosecurity/falco-website#1107]
**What is wrong with the website or needs to be cleaned?**

https://falco.org/docs/alerts/ may be confusing to adopters, plus one page in particular overlaps with Falco rules https://falco.org/docs/alerts/formatting/

Suggesting to work https://falco.org/docs/alerts/formatting/ into the style guide and then remove that page @leogr 

In addition, Falco rules vs Falco alerts what do we mean here? Rebranding the 2 remaining guides to `Falco Log Transport` could be a solution? WDYT?

@LucaGuerra @vjjmiras

**Comment by LucaGuerra** [comment]
I took another look at the page:

Personally, I find the wording "alerts" to be more intuitive than "Log Transport". At the end of the day, an Alert is an event that might require your attention which is also the main Falco output as explained the documentation. You can send your alert to several places if you need and that's what adopters want to do. When thinking about "log transport" I immediately think about application logs, which would make me more confused because they sound more like operational logs for Falco (maybe diagnostics or other things)

Re. Formatting rules, I think this does not necessarily belong in the style guide because it's something that a user may want to know when operating Falco, not only when writing rules. It is a good piece of information to know for the rule writer, but a k8s/container user that wants the right context for their alert will need to know it as well. Out of its current location and the style guide, I prefer where it is right now honestly.

**Comment by leogr** [comment]
I agree with @LucaGuerra.  

I think the _alert_ definition is clear :point_down: 
> Downstream actions executed after a rule is triggered.
> They can be as simple as logging to stdout or as complex as delivering a [gRPC](https://falco.org/docs/grpc/) call to a client.
_Falco Log Transport_ would be more confusing since an _alert_ (which sometimes I also call _notification_) is not always a log (for example, think the `gRPC` and the `program` output channels).

Furthermore, https://falco.org/docs/alerts/formatting/ is about telling Falco how to format the alert's message, not specifically about rules. For example, it's possible to run the same ruleset (that conforms to the rule styling guide) with different _Falco alert formatting_ settings. My standpoint is that they are logically separated.
So I recommend not rebranding/merging them. I'd rather suggest improving cross-linking (i.e., the style guide should have a link to the `-p` explanation of the alert formatting page and vice versa) and their definition if something is not yet crystal clear.

**Comment by incertum** [comment]
Hmmm where my head is right now since I do work in an operational settings and with SREs you always go through these items below in your head if you run some tool or service that produces logs, any logs really:

- How to install and update
- How to run
- How to configure
- How to get the data off host

This section should be about the "How to get the data off host" and we aren't concerned about terminology like alerts or logs, it's juts logs at the end of the day or data for that matter.  Perhaps then here we just use `Falco Output` or `Falco Output Channels` or something in that line, because in the config file we do not use alerts in this context and in fact use output and channels  https://github.com/falcosecurity/falco/blob/master/falco.yaml#L34

Just so folks who operate Falco and deploy Falco have a clearer picture on where to look when it comes to, ok how do I get the data out?

Something I believe we could improve, else I wouldn't have opened this ticket 🙃

**Comment by LucaGuerra** [comment]
I find Alerts quite intuitive, but Outputs is intuitive as well because it matches the configuration entry in the file, so I wouldn't be against changing the wording to Outputs if that makes it easier to understand at first glance. @leogr WDYT?

**Comment by leogr** [comment]
Ok, I privately discussed this with @incertum, and I believe we find a good solution. Using `Output` and `Output channels` makes sense, but also the `Alert` meaning must be preserved. So our proposal is summarized by this preview :point_down: 
![Screenshot from 2023-07-28 18-37-58](https://github.com/falcosecurity/falco-website/assets/3390997/d446c6b5-9cc8-400b-9aad-b2023f1dd0ad)

**Comment by LucaGuerra** [comment]
Makes sense to me.

**Comment by incertum** [comment]
Thank you!
