### ISSUE TITLE
Falco on Kind with Prometheus and Grafana

### ISSUE THREAD

**Issue by fjammes** [falcosecurity/falco-website#506]
/area documentation

**What would you like to be added**:

The section referenced by this link does not exists: https://falco.org/docs/getting-started/running/#running-falco-in-a-kind-cluster

**Why is this needed**:
Installing falco inside kind might be useful.

**Comment by jasondellaluce** [comment]
Hey @nicop311, just saw this issue. Since you seem to have found out the right link, would you like to open a PR to correct the broken one?

**Comment by nicop311** [comment]
Hi @jasondellaluce , I needed to understand what the problem was since I don't remember anything about this issue :sweat_smile: .

On the website : https://falco.org/blog/falco-kind-prometheus-grafana/, there is a section with a link which should explain how to use Falco with k8s KinD, but the section `#running-falco-in-a-kind-cluster` does not exist:

On the github, we can see the following: https://github.com/falcosecurity/falco-website/blob/b1852a801294fcd17dfef1473f1d5951d12ebd5e/content/en/blog/falco-kind-prometheus-grafana.md
```
[...]
## Create a Kind cluster
Running Falco in a Kind cluster is easy, as explained in the [documentation](https://falco.org/docs/getting-started/running/#running-falco-in-a-kind-cluster). 
[...]
```
The link is not broken, but the section `#running-falco-in-a-kind-cluster` about k8s KinD does not exist.

However the section **Running Falco in a Kind cluster** seems to exist here:
https://github.com/falcosecurity/falco-website/blob/06f1dcf52561100103fa379e5b60713e7fcb55aa/content/en/docs/running.md

But even on this `running.md` file, **there are not a lot of details on how to run/use Falco on KinD.**
**I did not tested Falco with KinD**, I personally went with Flatcar OS + k3s instead of KinD.

Plus, k8s KinD is using **nested containers** on top on Docker (k8s nodes are docker containers, k8s pods are running on the nodes). In this situation of nested containers, I do not know how the Falco eBPF probe or the kernel modules should be configured/installed.

Therefore, I am not confident about opening a PR to correct the link, since I am not sure the explanation is enough.
I hope this comment is useful though.

**Comment by jasondellaluce** [comment]
Thanks for spending time in explaining your point. That's still great feedback towards the quality of our docs. 👍🏼
