### ISSUE TITLE
(docs) json_output option influences `--version` output

### ISSUE THREAD

**Issue by Happy-Dude** [falcosecurity/falco-website#791]
ref: https://falco.org/docs/reference/daemon/config-options/

After https://github.com/falcosecurity/falco/pull/2351 has been merged in, `json_output=true` now influences the output of `falco --version`. As I commented in https://github.com/falcosecurity/falco/pull/2351#issuecomment-1397402538, this was surprising to me since it didn't use affect `--version`.

> This was surprising to me initially when pulling in the latest upstream changes because I expected json_output to only influence the output of the falco_events / alerts / logs; I did not expect this option to influence the output of --version.
>
> (My confusion was also compounded a user runs falco --version and doesn't have permissions to read /etc/falco/falco.yaml, so their output appeared as what I was familiar with whereas a script executing w/ the right context/permissions had the output in JSON.)

/area documentation

**What would you like to be added**:

* additional note that json_output influences the output of `falco --version`

**Why is this needed**:

* can become confusing when scripts parse the output (driver, engine versions, etc.) of `--version` and were not expecting JSON (which was the old behavior)

**Comment by jasondellaluce** [comment]
True! For more context, the rationale was that we're starting to need Falco outputs to be machine-readable. A first example is falcoctl that will need to inspect the version of a given Falco installation. The initial proposal was to add additional CLI flags, however we realized that it was a logical duplication due to `json_output` being already used to turn alerts and rule validation outputs into JSONs as well. 

Since this is a small change in the docs, would you be available to open a PR on the website?

**Comment by Happy-Dude** [comment]
Yessir! Apologies for the delay; will submit a PR soon(TM) with a quick blurb on the website.
